# Generated by Django 4.1.2 on 2022-11-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quatity_food',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
