# Generated by Django 4.1.2 on 2022-12-01 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow_getid', '0003_tvshow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
