# Generated by Django 4.1.2 on 2022-12-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_tvshow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TvShow',
        ),
    ]
