# Generated by Django 4.1.2 on 2022-12-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptops',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
