# Generated by Django 4.1.2 on 2022-12-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pars', '0002_laptops_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptops_pars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_laptop', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=6)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Laptops',
        ),
    ]
