# Generated by Django 4.1.2 on 2022-12-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pars', '0004_rename_laptops_pars_laptops_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
